### PR TITLE
Event handlers

### PR DESCRIPTION
**Pull request by MuriloRoque**
Dear TSE, hello! :wave:

Thank you for reviewing my project :grin:

Here's what I did in this milestone:

- Made the App a class component, initializing its state in the constructor with three properties: total, next, and operation. They are all set to null by default;
- Implemented render function that displays Display and ButtonPanel;
- Implemented the handleClick function which takes buttonName as an argument and changes the state based on the result of the calculate function;
- Passed the total or next value to Display to display the current result;
- Passed handleClick as a clickHandler property to ButtonPanel;
- Passed the clickHandler property to each button in the panel;
- Used the onClick event to attach the handleClick event to the button.

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @MuriloRoque , 

works perfectly

calc

### [changes required]

One more small details and we're good to go. PLease handle division by zero
Return an error, something like `NAN` or `INFINITY` etc...

Happy coding

**Comment by MuriloRoque** [comment]
I was trying to console log @shloch but the linter got an error. I think infinity is a good one! Thanks!

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @MuriloRoque, 👋 

### Amazing job implementing the suggested change! 💯 Just a few more bugs. 👇 

- [x] After pressing `=`, I should be able to start another operation entirely. Ways to reproduce below:
  - Press `2`
  - Press `+`
  - Press `54`
  - Press `=`
  - Press `3`
  - **`Desired result`:** _Start a fresh calculation with `3`_. 
  - **`Current result`:** _`563`_.

- [x] On pressing `%`, it should show the percentage of the value or shows it on pressing `=`. Steps to reproduce below:
  - Press `8`
  - Press `%`. 1. => Nothing changes
  - Press `=`. 2. => Nothing changes
  - **`Desired result`:** _Display `0.08` on pressing `%` in step 1 above or `=` in step 2_.
  - **`Current result`:** _`8%`_.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

**Review by suretrust — APPROVED** [review]
Hi @MuriloRoque, 👋 

### Amazing job fixing those bugs! 💯 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

**Comment by MuriloRoque** [comment]
Thank you very much @suretrust 😁

**Pull request merged**
